### ISSUE TITLE
Visual Studio 2015 or 2017?

### ISSUE THREAD

**Issue by therealkenc** [kennyzx/Broker_x64#1]
In the solution files, VisualStudioVersion = 12.0.31101.0. Is it necessary to download and install Visual Studio 2013 to run this example? Is there a way to adapt it to VS 2015 or 2017? I don't mind installing the older version to get going, but the rest of my project is on VS 2017 so I am going to have to adapt the solution files eventually. Thanks!

**Comment by kennyzx** [comment]
I just tried VS2015/17 on Windows 10, both failed to compile. I am afraid VS2013 is necessary to run the example.

**Comment by therealkenc** [comment]
Appreciate you giving it a try. After some struggling I managed to get the [Visual Studio 2015 project templates](https://marketplace.visualstudio.com/items?itemName=vs-publisher-713547.VS2015TemplateBrokeredComponents) working on VS2015 but not VS2017. I still had to fix up the  assembly reference paths for my Win10 environment. Everything keeps moving.

Anyway thanks for posting your code. I am glad someone else is actively developing brokered components (outside of Microsoft). I had just about given up and was going to use WCF over localhost.
